### PR TITLE
Document required sawtooth-core,validator build dependencies

### PR DESCRIPTION
**Pull request by jeremyeder**
Add a few missing steps to get the core code built/installed and validator built/installed/running.

### CODE REVIEW

**Comment by vaporos** [comment]
When using vagrant, these steps should be automatically performed during the first 'vagrant up' command.  Are you using vagrant?

If you aren't using vagrant, then these are very close to the right steps.  Inside vagrant though, we generally don't do an install and instead have PYTHONPATH setup.  It would be interesting to find an elegant way to allow either vagrant or install into a clean system (Ubuntu and CentOS would be nice, IMO) prior to the tutorial (choose your own adventure), if we can keep the overall complexity down.

**Comment by jeremyeder** [comment]
That surprised me too.  I was using your Vagrantfile.  I see now the bootstrap.d/20...file that should have done it.  Hmm.

**Comment by jeremyeder** [comment]
As far as elegant way ... the fabric project has a packer-based build pipeline that generates container images.  Something like that would be ideal (container images).

**Comment by vaporos** [comment]
Can you provide the output of 'vagrant box outdated'?  I'm on 20160406.0.0; some very old versions of this box apparently don't configure the repo we need for swig3.

**Comment by jeremyeder** [comment]
```
$ vagrant box outdated
Checking if box 'ubuntu/trusty64' is up to date...
$

$ vagrant box list | grep ubuntu
ubuntu/trusty64              (virtualbox, 20160406.0.0)
ubuntu/trusty64              (virtualbox, 20160509.1.0)
```

I had run vagrant box update earlier today which grabbed the new one.

**Comment by christo4ferris** [comment]
@vaporos bump

**Comment by vaporos** [comment]
Since this seems like an issue with outdated vagrant boxes, not a documentation problem per-se, resolving this PR.  Welcome some method to check for new-enough vagrant boxes in the sawtooth-dev-tools repo (maybe 'vagrant up' should fail early).

**Pull request closed without merging**
